# Generated by Django 2.0.3 on 2018-03-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(blank=True, default=0, max_length=50)),
                ('bcount', models.IntegerField()),
            ],
        ),
    ]
